name: Train and Evaluate Model

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: '10'

jobs:
  checkout_repo:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  train_model:
    name: Train the Model
    runs-on: ubuntu-latest
    needs: checkout_repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the model
        run: |
          python model.py --epochs ${{ github.event.inputs.epochs }}

  evaluate_model:
    name: Evaluate the Model
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Evaluate the model
        run: |
          python predict.py --model_path ./model_output
